import './globals.css'
import '@/tailwindcss/style.css'

import {Inter, Poppins} from 'next/font/google'
import NextTopLoader from "nextjs-toploader";
import {ToastContainer} from "react-toastify";
import process from "next/dist/build/webpack/loaders/resolve-url-loader/lib/postcss";

const inter = Inter({subsets: ['latin']})
const poppins = Poppins({
    weight: ['300', '400', '500', '600'],
    subsets: ['latin'],
})
export const metadata = {
    icons: {
        icon: `${process.env.NEXT_PUBLIC_BASE_URL}/images/logo.png`
    },
    title: {
        template: 'BWAMICRO | %s ',
        default: 'BWAMICRO', // a default is required when creating a template
    },
    description: 'Generated by create next app',
}

export default function RootLayout({children}) {
    return (
        <html lang="en">
        <body className={poppins.className}>
        <NextTopLoader/>
        {children}
        <ToastContainer position={"top-center"}></ToastContainer>
        </body>
        </html>
    )
}
